project:
  type: website

website:
  title: "Shiny rrisk user guide"
  navbar:
    left:
      - href: index.qmd
        text: Risk modelling

      - href: distributionfitting.qmd
        text: Distribution fitting
    
    right:
    - about.qmd

  page-footer: "Greiner M, Sanchez J, and who else contributes, 2025" 
  
  page-navigation: TRUE
  
  sidebar:
    style: "docked"
    search: true
    contents: /*
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
